### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by xe1os** [BeepIsla/CSGO-MajorVotes#1]
Hi BeepFelix,

Kudos for your work!! it would be great if you share the details on how to install this on a server.

Thanks,

**Comment by BeepIsla** [comment]
~~**Current this plugin is broken anyways and there is nothing I can do other than wait for Valve to fix stuff on their side.**~~

---

~~**Note:** You can't really use this as a standalone because Valve forces the teams of all players when setting the required Gamerule props, so you would require another plugin doing the team management stuff.~~

~~To change the tournament name you have to [edit line ~56 in plugin.sp](https://github.com/BeepFelix/CSGO-MajorVotes/blob/master/plugin.sp#L56), edit the string `"Tournament Test Event"` to what ever you want to call your tournament (Visible in the top left of the scoreboard)~~

~~To compile it you have to add the [`valve.inc` from powerlord to your includes folder where your compiler is](https://github.com/powerlord/sourcemod-tf2-scramble/blob/master/addons/sourcemod/scripting/include/valve.inc). The compiler can be found in `addons/sourcemod/scripting` and is called `spcomp.exe`.~~

~~Finally drag and drop the `plugin.sp` on top of the spcomp.exe, a window should pop up for a split second and then close itself again and you should find a compiled plugin.smx in the same folder as your plugin.sp.~~

~~That is your compiled version with custom tournament name.~~

---

~~If you don't care about the name of the tournament shown in the top left corner of the scoreboard you can just download a already compiled version [here](https://github.com/BeepFelix/CSGO-MajorVotes/releases).~~

~~I hope this was somewhat understandable. When I get time I will change some stuff so you can set the tournament name using a convar and no longer need the valve.inc from powerlord.~~

---

None of this applies anymore. Just compile it by dragging the `plugin.sp` ontop of your spcomp.exe and everything should be good to go. *[(or just use the pre-compiled version)](https://github.com/BeepFelix/CSGO-MajorVotes/releases)* Use the added convars to adjust gameplay.

**Comment by xe1os** [comment]
@BeepFelix Thank you again for the help :)

**Comment by BeepIsla** [comment]
Valve has finally updated the game to fix issues with the vote UI.

I have updated the plugin, added some convars and fixed some bugs.
